name: Run Playwright Tests

on:
  push:
   branches:
    - main
  schedule:
    - cron: "0 0 * * 5"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run tests with Playwright
      run: npm test
